-- 041_oracle_sync_messages_and_fk_repoint.sql
-- Documents the Oracle identity + conversation tables and corrects user_id
-- foreign keys that were mistakenly pointing at auth.users instead of public.users.
-- These tables were originally created as hand-made live state with no migration;
-- this file records their real shape and the corrected constraints. Idempotent and
-- safe to re-run against a database where the fixes are already applied.

-- ── oracle_sync: the user's "Book of You" (birth profile) ──
CREATE TABLE IF NOT EXISTS public.oracle_sync (
  user_id          uuid PRIMARY KEY,
  birth_name       text,
  birth_date       text,
  birth_time       text,
  birth_place      text,
  current_location text,
  path_focus       text,
  life_details     text,
  created_at       timestamptz DEFAULT now(),
  updated_at       timestamptz DEFAULT now()
);

-- ── oracle_messages: persisted Oracle conversation history ──
CREATE TABLE IF NOT EXISTS public.oracle_messages (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    uuid NOT NULL,
  role       text,
  content    text,
  created_at timestamptz DEFAULT now()
);

-- ── Correct all four user_id foreign keys to reference public.users ──
-- Each is dropped-if-exists then re-added pointing at public.users(id).

ALTER TABLE public.oracle_sync      DROP CONSTRAINT IF EXISTS oracle_sync_user_id_fkey;
ALTER TABLE public.oracle_sync      ADD  CONSTRAINT oracle_sync_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE public.oracle_messages  DROP CONSTRAINT IF EXISTS oracle_messages_user_id_fkey;
ALTER TABLE public.oracle_messages  ADD  CONSTRAINT oracle_messages_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE public.profile_videos   DROP CONSTRAINT IF EXISTS profile_videos_user_id_fkey;
ALTER TABLE public.profile_videos   ADD  CONSTRAINT profile_videos_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE public.profile_music    DROP CONSTRAINT IF EXISTS profile_music_user_id_fkey;
ALTER TABLE public.profile_music    ADD  CONSTRAINT profile_music_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
