-- 117_oracle_messages_uuid_id.sql
--
-- oracle_messages — A DECISION, then a transcription.
--
-- ── WHAT WAS FOUND ────────────────────────────────────────────────────────
--
-- 041 creates the table with
--
--   id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
--
-- The live table, read from PostgREST's schema description and pg_constraint
-- on 2026-09-15, has
--
--   id  uuid  NOT NULL  DEFAULT gen_random_uuid()   (oracle_messages_pkey)
--
-- and 26 rows, every one of them carrying a uuid. Two smaller divergences in
-- the same table:
--
--   user_id   041: uuid NOT NULL          live: uuid, nullable
--   role      041: no constraint          live: oracle_messages_role_check
--                                               CHECK (role IN ('user','assistant'))
--
-- The foreign key oracle_messages_user_id_fkey (ON DELETE CASCADE) is in 041
-- and matches live exactly. created_at, content and role match.
--
-- ── THE DECISION: THE LIVE SHAPE IS RIGHT AND 041 IS WRONG ────────────────
--
-- This is not a case where the migration expresses the intent and the
-- database drifted from it. The database is the thing that has been running:
-- 26 rows of a real person's Oracle conversation are keyed by uuid, the
-- oracle_sync table that 041 creates in the same file is keyed by uuid, every
-- other table in this schema is keyed by uuid with the same default, and the
-- application never treats the id as a number — server.js reads
-- oracle_messages by user_id ordered by created_at and never by id, so
-- nothing in the code ever wanted a bigint. 041's identity column is the one
-- table in the directory that breaks the schema's own convention, and it does
-- so with no reason recorded for it.
--
-- The deciding argument is the data. A restore of the 26 live rows into 041's
-- table fails outright: '5bbb4ddf-0b4d-4553-a50f-7c089deeaf57' is not a
-- bigint. The live shape can hold everything that exists. 041's shape cannot.
-- Making the migration match reality costs nothing; making reality match the
-- migration means rewriting 26 primary keys for no benefit.
--
-- ── WHAT A REBUILD DOES WITHOUT THIS FILE ─────────────────────────────────
--
-- 041 builds the bigint table. The application runs against it without error
-- — inserts omit id and the identity supplies one — so the divergence is
-- invisible until a restore is attempted, at which point the Oracle's
-- conversation history is the one table whose backup cannot be loaded. The
-- nightly backup (lib/backup.js) includes oracle_messages, so this is a
-- backup that has been faithfully taken and could not be used.
--
-- ── HOW THIS FILE CORRECTS A REBUILD, AND WHY IT CANNOT BE PURELY ADDITIVE ─
--
-- A column's type cannot be added to. The only way for a rebuild that ran 041
-- to land on the live shape is to change id from bigint to uuid, and that is
-- an ALTER. It is written here under a DOUBLE GUARD so that it can only ever
-- act on a freshly-built, empty table and never on a live one:
--
--   1. id must currently be bigint. Live is uuid, so live is excluded by type.
--   2. the table must hold zero rows. A rebuild has written nothing yet; a
--      live table has 26. If a bigint table somehow had rows, this file
--      refuses with a notice rather than inventing uuids for them.
--
-- Against the live database the block finds a uuid column and does nothing.
-- The identity sequence is dropped with the identity; the primary key
-- constraint survives the type change unchanged.
--
-- ── THE TWO SMALLER DIVERGENCES ───────────────────────────────────────────
--
-- user_id nullable: 041 says NOT NULL, live is nullable. Transcribed as live.
-- A no-op live (already nullable), a relaxation on a rebuild. Whether the
-- nullability was deliberate is unrecorded; the FK's ON DELETE CASCADE means
-- a NULL user_id can only arise from an insert that omitted it, and no live
-- row has one. It is transcribed rather than tightened because tightening is
-- a change and this file is not one.
--
-- role check: exists live, not in 041. Added guarded on its name. The values
-- are the two the Oracle route writes.
--
-- ── SAFETY ────────────────────────────────────────────────────────────────
--
-- Every statement is guarded and re-runnable. No row is written, updated or
-- deleted. Nothing that exists on the live database is dropped or altered:
-- the type change is reachable only through a guard the live table cannot
-- satisfy. No existing file is renumbered — 116 was the highest before this.

-- ── REBUILD-ONLY: bigint identity → uuid, on an empty table only ──────────
do $$
declare
  current_type text;
  row_count    bigint;
begin
  select format_type(a.atttypid, a.atttypmod)
    into current_type
  from pg_attribute a
  where a.attrelid = 'public.oracle_messages'::regclass
    and a.attname = 'id'
    and not a.attisdropped;

  if current_type = 'uuid' then
    -- Live, or an already-corrected rebuild. Nothing to do.
    return;
  end if;

  if current_type is distinct from 'bigint' then
    raise notice '117: oracle_messages.id is % — neither uuid nor bigint; left untouched', current_type;
    return;
  end if;

  select count(*) into row_count from public.oracle_messages;
  if row_count > 0 then
    raise notice '117: oracle_messages.id is bigint and the table holds % row(s); refusing to change the type of a populated table', row_count;
    return;
  end if;

  alter table public.oracle_messages
    alter column id drop identity if exists;
  alter table public.oracle_messages
    alter column id type uuid using gen_random_uuid();
  alter table public.oracle_messages
    alter column id set default gen_random_uuid();
end $$;

-- ── user_id: nullable live ────────────────────────────────────────────────
do $$
begin
  if exists (
    select 1 from pg_attribute
    where attrelid = 'public.oracle_messages'::regclass
      and attname = 'user_id' and attnotnull and not attisdropped
  ) then
    alter table public.oracle_messages alter column user_id drop not null;
  end if;
end $$;

-- ── role check: live, not in 041 ──────────────────────────────────────────
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'oracle_messages_role_check'
      and conrelid = 'public.oracle_messages'::regclass
  ) then
    alter table public.oracle_messages
      add constraint oracle_messages_role_check
      check (role in ('user', 'assistant'));
  end if;
end $$;

COMMENT ON COLUMN public.oracle_messages.id IS
  'uuid, DEFAULT gen_random_uuid(). Migration 041 declared this as bigint GENERATED AS IDENTITY; the live table was never that, and migration 117 records the decision to keep the live uuid — every other table in this schema is uuid-keyed, the application never reads this id as a number, and the 26 live rows cannot be restored into a bigint column. 117 converts a freshly-rebuilt bigint table to uuid only while it is empty.';
